apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: demo
  selector:
    app: demo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - image: platformcustom/gitops:80d8b98
        imagePullPolicy: IfNotPresent
        name: demo
        ports:
        - containerPort: 3000
          name: demo
