name: Build, Test, Docker Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6


      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package.json') }}
          restore-keys: |
            v1-dependencies-

      - name: Install node packages
        run: yarn install

      - name: Start app
        run: yarn start &

      - name: Run tests
        run: yarn test

      - name: Save node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package.json') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: platformcustom
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: platformcustom/gitops:${{ env.SHORT_SHA }}
